### ISSUE TITLE
[Epic] Sprint Exit Metrics

### ISSUE THREAD

**Issue by devendran-m** [block-bites/zenhub-advanced-dashboard#1]
This is an epic to track the creation of **Sprint Exit Metrics** features. 

### Pain point:
Sprint Exit is a critical phase of the Sprint Cadence. During the exit, there are critical data points that a Program/Project Manager have to manually gather data, clean up, collate and analyse the inferences those data points had to offer.
In the current Zenhub managed sprints, some of these steps require manual intervention and require considerable human effort to produce reports on each Sprint Exit time. 

### Epic Objective:
As a Program/Project Manager, I would like to have the following list of metrics automatically calculated and available on a dashboard or presentable/downloadable format to me to calculate the success of a Sprint. I expect to use those metrics to give me insights on how the sprint has progressed, gain an understanding of challenges and/or risks that impacted the sprint cycle and other useful information that can be converted into actionable next steps.

### User Stories: 

- [ ] Planned vs. Actual completed user stories in numbers & percentage
- [ ] Sprint Velocity incl. Current Sprint Velocity, Average Sprint Velocity 
- [ ] Velocity Trend based on all completed sprints
- [ ] Scope Change - added vs. removed user stories in numbers and in percentage
- [ ] Scope Change - Net scope added/removed in numbers and in percentage
- [ ] Scope Change graph depicting additions/removals datewise
- [ ] Net Scope Change trend line based on completed sprints so far
- [ ] No. of pending stories and the story points at the time of Sprint Exit, categorised by pipeline
- [ ] Facility to add categorisation tag to rolled over stories for Sprint Retrospective
- [ ] Overall Rolled Over Stories categorisation and trend chart (based on all completed sprints)
- [ ] Anomalies - Longest running stories/Aged stories

### Definition of Done [DoD]
Please find the common definition of done for this Epic and its related stories. Individual story level Definition of Done will be specified in the respective user stories.

**Common expectations:** 
1. Data presented on the screen/dashboard and/or within individual data tiles/containers/window should be accurate and match the information on the respective Zenhub Dashboard/Organisation.
2. The expectation is that each user story listed below should be an easily configurable, filterable and exportable data widget or tile on the dashboard.
3. Filtering option should allow user to filter by;
     - sprints [based on from and to date as set up in Zenhub] 
     - repositories [should allow multi-select] 
     - team(s) [should allow multi-select]
     - team members [should allow multi-select] 
4. Data widget or dashboard tile of the metric should allow dynamic rendering of the graphs, charts, trend lines based on the filtering option selected
